### ISSUE TITLE
970x250 || All Browser || Default || The arrow icons is not appearing as Ref 728x90

### ISSUE THREAD

**Issue by mahmudur-sebpo** [sebpo1/USCS_2048#1]
Issue:

https://user-images.githubusercontent.com/106811939/215221855-8a47ee08-64d4-4fae-8248-17218a205448.mp4

Ref 728x90:

https://user-images.githubusercontent.com/106811939/215222054-400e0fc5-70c4-44aa-968c-c75ed5297e09.mp4

**Comment by AbiirHossen09** [comment]
Fixed

**Comment by mahmudur-sebpo** [comment]
Issue resolved
