### ISSUE TITLE
970x250 | All browser(W, M) | overlapping with black BBY logo while transition

### ISSUE THREAD

**Issue by susmita-sebpo** [sebpo1/USCS_2048#10]
Q32022_VideoGames | 
Q32022_Smart_Home
Q32022_Printers_Ink_and_Toner

![image](https://user-images.githubusercontent.com/100709063/216572358-8ed6d655-f08d-4e2a-a313-7e31cb190829.png)
![image](https://user-images.githubusercontent.com/100709063/216573336-4a4cd7e0-e47d-45cd-a279-c3ca12c0f935.png)
![image](https://user-images.githubusercontent.com/100709063/216573547-8536e77d-8ac8-4ed2-9e89-b3ba10980e73.png)

**Comment by AbiirHossen09** [comment]
Fixed

**Comment by susmita-sebpo** [comment]
fixed
