### ISSUE TITLE
728x90 | All browser(W, M) | overlapping with black BBY logo while transition

### ISSUE THREAD

**Issue by susmita-sebpo** [sebpo1/USCS_2048#11]
Q32022_Computers_and_More
Q32022_Generic_Default
Q32022_Health_and_Wellness
Q32022_Home_Theater_Audio_and_More
Q32022_Laptops_Tablets_and_More
Q32022_Printers_Ink_and_Toner
Q32022_Smart_Home
Q32022_TVs_Projectors_and_More
Q32022_VideoGames
![image](https://user-images.githubusercontent.com/100709063/216580207-39736550-bf55-4313-b1a2-7fa9ee8534fc.png)
![image](https://user-images.githubusercontent.com/100709063/216580299-0e7964b9-39cb-45eb-b1d7-66c6a4d4553b.png)
![image](https://user-images.githubusercontent.com/100709063/216580377-4c47d9d8-d79d-424e-ab38-2d446ca51530.png)
![image](https://user-images.githubusercontent.com/100709063/216580460-03bf6628-943c-46a0-9845-645dde591614.png)
![image](https://user-images.githubusercontent.com/100709063/216582125-453d99b8-4df2-44b6-9a99-e9482f1a735a.png)
![image](https://user-images.githubusercontent.com/100709063/216582301-23e6abaa-e086-4c94-8198-0b4016ad2b1a.png)
![image](https://user-images.githubusercontent.com/100709063/216582370-5d17d05d-7f6b-4359-be24-c99ebfd5d1df.png)

**Comment by AbiirHossen09** [comment]
Fixed

**Comment by susmita-sebpo** [comment]
fixed
