### ISSUE TITLE
300x600| all versions | all browsers | last frame | CTA not horizontally center aligned according to feedback

### ISSUE THREAD

**Issue by mithila-sebpo** [sebpo1/USCS_2048#17]
![image](https://user-images.githubusercontent.com/95068780/217879624-55de7034-4c2c-42e3-997a-ada3eb86991f.png)
![image](https://user-images.githubusercontent.com/95068780/217879848-dd2c87dc-85dc-4b68-9ae0-bb0263b1516e.png)

**Comment by AbiirHossen09** [comment]
Fixed

**Comment by mithila-sebpo** [comment]
solved
