### ISSUE TITLE
970x250 || All Browser || Default || Headline should be appeared later after appearing image slider as Ref 728x90

### ISSUE THREAD

**Issue by mahmudur-sebpo** [sebpo1/USCS_2048#2]
Issue:

https://user-images.githubusercontent.com/106811939/215223265-f95d2f8e-cd96-4c5a-af39-68a13861c89c.mp4

Ref: 

https://user-images.githubusercontent.com/106811939/215223210-b4a6ed2b-c786-4155-ba3e-b4997165d18e.mp4

**Comment by abdurSebpo** [comment]
fixed

**Comment by mahmudur-sebpo** [comment]
Issue resolved
