### ISSUE TITLE
970x250 | All version | 'backup_img : Image' should 970x250 instead of 728x90

### ISSUE THREAD

**Issue by arnab-sebpo** [sebpo1/USCS_2048#4]
![image](https://user-images.githubusercontent.com/95363813/215740507-b7277d72-1b87-4bdc-b4d4-d3c410be2368.png)

**Comment by abdurSebpo** [comment]
uploaded 970x250 fallback image

**Comment by arnab-sebpo** [comment]
fixed

![image](https://user-images.githubusercontent.com/95363813/215762073-8487271f-6ae0-41b9-a1a7-2792d7c9f3e9.png)
