### ISSUE TITLE
All size | Q32022_Smartwatches_and_More | All browser(W, M) | loading issue

### ISSUE THREAD

**Issue by susmita-sebpo** [sebpo1/USCS_2048#9]
![image](https://user-images.githubusercontent.com/100709063/216571134-9567f6fa-48f1-4ff6-a00e-9908369dcb5f.png)
![image](https://user-images.githubusercontent.com/100709063/216590697-889bd854-96fb-4eb4-a4d7-5650f3ee3a00.png)

**Comment by AbiirHossen09** [comment]
https://flashtalkingus.atlassian.net/browse/USCS-2048?focusedCommentId=1091405
Because of the feedendpoint the version is not working. For that please check the above comment link.

**Comment by susmita-sebpo** [comment]
fixed
